### ISSUE TITLE
"Move" table rows are broken at width over 767px

### ISSUE THREAD

**Issue by SirDieter** [HybridShivam/pokedex-angular-app#2]
In the pokemon detail component the move table rows are broken for me if the viewport width is over 767px. Up to 767px everything is fine.
Here is a screenshot of the bugged table (butterfree's moves).
![pokedex error](https://user-images.githubusercontent.com/12086930/84486814-314a8900-ac9e-11ea-8263-bce23dfd0065.PNG)
Browser: Google Chrome 83.0.4103.97

**Comment by HybridShivam** [comment]
I'll look into it asap !!! thanks

**Comment by HybridShivam** [comment]
![image](https://user-images.githubusercontent.com/28728749/84487558-90b79180-acbc-11ea-95cd-b7a7d3d575e0.png)
![image](https://user-images.githubusercontent.com/28728749/84487597-9ca35380-acbc-11ea-855e-159f7b24f49b.png)

**Comment by SirDieter** [comment]
Hm. I tried disabling my browser plugins, used incognito mode and opened the website in the old Microsoft Edge and everywhere the table was bugged for me. I'm not sure what else I can do and what information I can give to you.
Here are some screenshots with the responsive viewport in the chrome dev tools.
![pokedex works](https://user-images.githubusercontent.com/12086930/84492192-1b40c680-aca6-11ea-958c-3d58d2f46439.PNG)
![pokedex error with width](https://user-images.githubusercontent.com/12086930/84492194-1c71f380-aca6-11ea-9763-87fee08feef6.PNG)

**Comment by HybridShivam** [comment]
Seems a serious issue it occured when I was working and was due to oversized Category icons but i fixed it and haven't encountered it on any device and now your screenshot confuses me.

**Comment by SirDieter** [comment]
Disabling this css rule fixes it for me 
![pokedex css](https://user-images.githubusercontent.com/12086930/84495621-bd16e200-acab-11ea-8837-d7e8a1730fd1.PNG)

**Comment by HybridShivam** [comment]
I'll have to check see if it doesn't break it for others

**Comment by HybridShivam** [comment]
> Disabling this css rule fixes it for me
> ![pokedex css](https://user-images.githubusercontent.com/12086930/84495621-bd16e200-acab-11ea-8837-d7e8a1730fd1.PNG)

But this causes the table to not be scrollable anymore and it expands to its full height

**Comment by HybridShivam** [comment]
As I said earlier its about the damage category icons :
`
.damage-icon {
    max-width: 33px;
}
`
This applies to >=768px
If you'll reduce it will be okay , but I don't get it why this happens for you only.

**Comment by HybridShivam** [comment]
For instance if I purposely increase it to 34px then it happens otherwise its always perfect.
![image](https://user-images.githubusercontent.com/28728749/84496564-c9f6fe00-acca-11ea-81a2-5db688404c71.png)
33px works perfect for me , check the same for you.

**Comment by SirDieter** [comment]
I think I found the problem. The table works for me on my main display, but not on my secondary display. The secondary display has the text scale in windows settings set to 200%, the main display has it set to 125%.

**Comment by HybridShivam** [comment]
So, in that case, 
https://stackoverflow.com/questions/49894991/windows-screen-scale-messing-up-css-sizes

**Comment by HybridShivam** [comment]
@SirDieter Wait for the next update Got the fix :

**Comment by HybridShivam** [comment]
Code Updated, Will update website in a few hours.
